version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sparkles_hyperbunny77/realdebridmanager_1
      APP_PORT: 5000
    
  server:
    image: hyperbunny77/realdebridmanager:2022.06.27
    user: "1000:1000"
    init: true
